import { useAuthContext } from "@/context/AuthContext";

export function useAuth() {
  const {
    firebaseUser,
    user,
    profile,
    completionItems,
    isAuthenticated,
    loading,
    error,
    clearError,
    loginWithGoogle,
    loginWithEmail,
    signupWithEmail,
    logout,
    deleteAccount,
    updateProfileData,
    updateAvatar,
    dismissOnboarding,
    isQuickAuthOpen,
    setIsQuickAuthOpen,
    isOnboardingOpen,
    setIsOnboardingOpen,
    isProfileViewOpen,
    setIsProfileViewOpen,
    checkEventRegistrationFields,
    role,
  } = useAuthContext();

  return {
    firebaseUser,
    user,
    profile,
    completionItems,
    isAuthenticated,
    loading,
    error,
    clearError,
    role,
    participantType: user?.participantType || null,
    profileCompletion: user?.profileCompletion || 0,
    requiredFieldsCompleted: user?.requiredFieldsCompleted || false,
    loginWithGoogle,
    loginWithEmail,
    signupWithEmail,
    logout,
    deleteAccount,
    updateProfileData,
    updateAvatar,
    dismissOnboarding,
    isQuickAuthOpen,
    setIsQuickAuthOpen,
    isOnboardingOpen,
    setIsOnboardingOpen,
    isProfileViewOpen,
    setIsProfileViewOpen,
    checkEventRegistrationFields,
  };
}
